config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts, except: :index do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  devise_for :users
  root 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

# The Category of Post
class Category < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { in: 2..50 }

  has_many :posts, dependent: :destroy
end

app/models/post.rb
# frozen_string_literal: true

# Model of Posts
class Post < ApplicationRecord
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy
  belongs_to :category
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id', inverse_of: :posts

  validates :title, presence: true, length: { in: 5..255 }
  validates :body, presence: true, length: { in: 200..4000 }
end

app/models/post_comment.rb
# frozen_string_literal: true

# Model of comments to post
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_ancestry

  validates :content, presence: true
end

app/models/post_like.rb
# frozen_string_literal: true

# count of Likes in post
class PostLike < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
# frozen_string_literal: true

# User with auth
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy, inverse_of: :creator
  has_many :post_comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!

  def create
    @comment = @post.comments.build(comments_params)
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post), notice: t('comment.actions.created')
    else
      redirect_to post_path(@post), alert: t('comment.actions.cant_create')
    end
  end

  def destroy
    @comment = PostComment.find(params.expect(:id))
    if @comment.user == current_user
      @comment.destroy!

      redirect_to post_path(@post), notice: t('comment.actions.deleted')
    else
      redirect_to post_path(@post), notice: t('comment.actions.not_creator')
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comments_params
    params.expect(post_comment: %i[content parent_id])
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @like = @post.likes.find_or_create_by(user: current_user)

    redirect_to @post
  end

  def destroy
    @like = @post.likes.find(params[:id])

    @like.destroy if @like.user == current_user
    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create edit destroy update]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc).includes(:creator)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    return unless @post.creator != current_user

    redirect_to @post, notice: t('post.actions.not_creator')
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.creator = current_user if @post.new_record?

    if @post.save
      redirect_to @post, notice: t('post.actions.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if @post.creator == current_user
      if @post.update(post_params)
        redirect_to @post, notice: t('post.actions.updated')
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to @post, notice: t('post.actions.not_creator')
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    if @post.creator == current_user
      @post.destroy!

      redirect_to root_path, status: :see_other, notice: t('post.actions.deleted')
    else
      redirect_to @post, notice: t('post.actions.not_creator')
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.expect(post: %i[title body category_id user_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/comments/_comment.html.slim
.card
  .card-body
    .media
      .media-body
        .card-title
          h6 = comment.user.email
        .card-body
          p.card-text = comment.content

        - if comment.user == current_user
          = link_to t('comment.destroy'), post_comment_path(comment.post, comment.id),
            data: { 'turbo-method': :delete, 'turbo-confirm': t('actions.confirm') },
            class: 'btn btn-sm btn-link'
        - if user_signed_in?
          = link_to t('comment.respond'), "#reply-form-#{comment.id}",
          class: 'btn btn-sm btn-link', data: { bs_toggle: 'collapse' }

        div id="reply-form-#{comment.id}" class="collapse mt-2"
          = render 'comments/form',
          post: comment.post,
          comment: comment.post.comments.new,
          parent_id: comment.id

        - if comment.children.any?
          .card-footer
            h6 = t('comment.replies')
            - comment.children.each do |child|
              .card.mb-3
                = render 'comments/comment', comment: child

app/views/comments/_form.html.slim
= simple_form_for([post, comment], url: post_comments_path(post)) do |f|
  .form-inputs
    = f.input :content, label: t('comment.form_label'), required: false
    = f.hidden_field :parent_id, value: parent_id if defined?(parent_id)

  .form-actions
    = f.button :submit, t('comment.submit'), class: 'btn btn-outline-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title = content_for(:title) || t('application.title')
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="mobile-web-app-capable" content="yes"
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    / Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!)
    / = tag.link rel: "manifest", href: pwa_manifest_path(format: :json)

    link rel="icon" href="/icon.png" type="image/png"
    link rel="icon" href="/icon.svg" type="image/svg+xml"
    link rel="apple-touch-icon" href="/icon.png"

    / Includes all stylesheet files in app/assets/stylesheets
    = stylesheet_link_tag :app, 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'

  body.d-flex.flex-column
    = render 'layouts/shared/navbar'
    main.flex-shrink-0 style='padding-top: 60px;'
      = render 'layouts/shared/alert'
      .container
        = yield
    footer.footer.mt-auto.py-3.bg-light
      .container
      span.text-muted = t('application.footer', year: Time.current.year)

app/views/layouts/shared/_alert.html.slim
- if flash.any?
  .container.my-2
    - flash.to_hash.each_value do |msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_navbar.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top
  .container-fluid
    = link_to t('application.title'), root_path, class: 'navbar-brand'
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
      span.navbar-toggler-icon
    #navbarCollapse.collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-md-0
        - if user_signed_in?
          li.nav-item
            = link_to t('navbar.new'), new_post_path, class: 'nav-link'
      ul.navbar-nav.ms-auto.mb-2.mb-md-0
        - if user_signed_in?
          li.nav-item
            = link_to t('navbar.signout'), destroy_user_session_path, class: 'nav-link', data: { 'turbo-method': :delete, 'turbo-confirm': t('actions.confirm') }
        - else
          li.nav-item
            = link_to t('navbar.signup'), new_user_registration_path, class: 'nav-link'
          li.nav-item
            = link_to t('navbar.login'), new_user_session_path, class: 'nav-link'

app/views/likes/_like.html.slim
- if user_signed_in?
  - @like = post.likes.find_by(user_id: current_user)
  - if @like.nil?
    = link_to post_likes_path(post),
    data: { 'turbo-method': :post }, class: 'btn' do
      i.bi.bi-hand-thumbs-up
  - else
    = link_to post_like_path(post, @like.id),
    data: { 'turbo-method': :delete }, class: 'btn' do
      i.bi.bi-hand-thumbs-up-fill
- else
  i.bi.bi-hand-thumbs-up

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification
   message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, label: t('simple_form.labels.post_title'), required: false
    = f.input :body, label: t('simple_form.labels.post_body'), required: false
    = f.association :category, label: t('simple_form.labels.post_category')

  .form-actions
    = f.submit @post.new_record? ? t('simple_form.labels.submit_new') : t('simple_form.labels.submit_edit'), class: 'btn btn-success'

app/views/posts/_post.html.slim
div id="#{dom_id post}"
  h1 = post.title
  p = post.body
  .creation_info
    p.small = post.creator.email
    p.small = post.created_at

app/views/posts/edit.html.slim
h1 = t('post.actions.edit')

== render 'form', post: @post

br

div
  => link_to t('post.show'), @post
  '|
  =< link_to t('post.back'), posts_path

app/views/posts/index.html.slim
h1 = t('application.title')

#posts
  - @posts.each do |post|
    .card.mb-3.rounded.shadow
      .card-body
        h2.h5.card_title = link_to post.title, post, class: 'text-decoration-none text-dark'
        .card-text.mb-2
          = post.body.truncate(300)
        .text-right.small.text-muted.mt-auto
          span.me-2 = "#{t('post.liked_by')} #{post.likes_count}"
          span.me-2 = distance_of_time_in_words(post.created_at, Time.now.utc)
          span = post.creator.email

app/views/posts/new.html.slim
h1 = t('post.actions.new')

== render 'form', post: @post

br

div
  = link_to t('post.back'), root_path

app/views/posts/show.html.slim
p.small
  = link_to t('post.posts'), root_path
  = "/#{@post.category.name}"

== render @post

.d-flex.justify-content-between.mt-5.mb-2
  div
    = link_to t('post.back'), root_path, class: 'btn btn-outline-primary me-2'
    - if @post.creator == current_user
      = link_to t('post.edit'), edit_post_path(@post), class: 'btn btn-outline-primary me-2'
      = link_to t('post.delete'), post_path(@post),
       data: { 'turbo-method': :delete, 'turbo-confirm': t('actions.confirm') },
       class: 'btn btn-outline-danger'
  .likes-section
    span = @post.likes_count
    = render 'likes/like', post: @post

- if @post.comments.any?
  h2 = t('comment.comments')

- if user_signed_in?
  = render 'comments/form', post: @post, comment: @post.comments.new,
  parent_id: params[:parent_id]

br

- @post.comments.roots.each do |comment|
  = render 'comments/comment', comment: comment
  br